### ISSUE TITLE
谢谢大佬，请问宝塔如何安装。

### ISSUE THREAD

**Issue by hietsusama** [Hackxiaoya/CuteOne#3]
首先先谢谢大佬无私奉献（鞠躬

顺便想问问大佬有计划出宝塔的安装教程嘛，小鸡都是装的宝塔环境

**Comment by kenzie-wu** [comment]
看教程啊！[https://wiki.cuteone.cn/cuteone-an-zhuang](https://wiki.cuteone.cn/cuteone-an-zhuang)

**Comment by Insightfy** [comment]
我错了！！！感谢大佬！！！ 

> 看教程啊！https://wiki.cuteone.cn/cuteone-an-zhuang
