### ISSUE TITLE
前台页面`负载磁盘`中无网盘选项

### ISSUE THREAD

**Issue by dasnnj** [Hackxiaoya/CuteOne#32]
**首先感谢作者开源的好项目**
#### 我这边版本是v2.2.0 ，然后一个驱动里有两个网盘，但是前台页面鼠标浮在`负载磁盘`上没有弹出下面的磁盘菜单选项
![image](https://user-images.githubusercontent.com/24741477/56953716-bb559200-6b6f-11e9-9bea-2dbc46f48de3.png)
![image](https://user-images.githubusercontent.com/24741477/56953988-420a6f00-6b70-11e9-90c6-c89759b604cd.png)
不知道是bug还是我这边操作有误？

**Comment by Hackxiaoya** [comment]
我还没修复

**Comment by Hackxiaoya** [comment]
@dasnnj 已修正
