### ISSUE TITLE
按照#21修改之后还是无法播放视频，群里面的影视模块安装也提示失败

### ISSUE THREAD

**Issue by LoogCP** [Hackxiaoya/CuteOne#38]

**Comment by LoogCP** [comment]
不知道是不是我权限设置还是啥没弄对，不能播放，也不能下载。。。下载提示504

**Comment by Hackxiaoya** [comment]
504是你反代问题吧。

**Comment by LoogCP** [comment]
> 504是你反代问题吧。

我好想是添加的网盘错了，现在能播放了，但是没有声音（mp4格式），mkv格式不能播放，点击直接就询问是否下载

还有就是把群文件里面的影音模块上传到app/model里面，安装提示失败。。。。是不是需要手动设置movie文件的权限呀

**Comment by Hackxiaoya** [comment]
播放没声音或者没画面是编码问题，MKV也能播放，也是编码问题；  
群共享的影视模块要求数据是5.7 如果低于5.7是失败的。因为那只是个演示版。
