### ISSUE TITLE
前来赞美大佬，顺带汇报一个小小的问题。

### ISSUE THREAD

**Issue by mqdlzh** [Hackxiaoya/CuteOne#51]
在CuteOne3.0 中的install.sh
![20190531185150](https://user-images.githubusercontent.com/31967654/58701394-5a6ee300-83d5-11e9-8610-5afb11a06502.png)
shell 运行报错 [: =: unary operator expected

![20190531184912](https://user-images.githubusercontent.com/31967654/58701205-dcaad780-83d4-11e9-92f3-9f3b8819c30e.png)
解决办法：原网页 https://blog.csdn.net/h106140873/article/details/78383467
![20190531185242](https://user-images.githubusercontent.com/31967654/58701416-678bd200-83d5-11e9-8425-0791a0360438.png)

然后顺带问一问如果可能是否可以改用Redis，或者提供一些指导，外行人不懂怎么改。

**Comment by Hackxiaoya** [comment]
shell脚本水平有限。如果你有shell脚本经验 可以群里at我。。。然后暂不支持redis。因为他太吃内存了。

**Comment by mqdlzh** [comment]
![20190531200340](https://user-images.githubusercontent.com/31967654/58704614-3dd7a880-83df-11e9-81c1-36cfc0b26317.png)

emmm，真外行人，就是看过博客介绍过来的，shell因为用过linux所以有一点点点的基础，但python和php有关的全都不懂。。。

是不是我的mongod数据库没配置正确？（ mongodb: command not found）
![20190531200707](https://user-images.githubusercontent.com/31967654/58704843-f4d42400-83df-11e9-92ae-69f48963035b.png)

![20190531200803](https://user-images.githubusercontent.com/31967654/58704844-f69de780-83df-11e9-8dcd-091e151572cc.png)

**Comment by mqdlzh** [comment]
emmmm感觉貌似不是mongo的问题了。。。放弃使用3.X版本，按照wiki一步一步就有成功了。那是install.sh里有些纰漏了。。。
![20190531202543](https://user-images.githubusercontent.com/31967654/58705717-9c525600-83e2-11e9-88e9-df555782a71b.png)

**Comment by mqdlzh** [comment]
没加群，QQ，贴吧已经不接触了，一般就是在知乎和各种小博客出没。刚刚安装完成才知道原理插件模块要收费，不过我也理解，用爱发电，做好就像应该的，做错就只能挨骂。这种事情习惯了。所以我也没打算白嫖什么，体验一下就行了。
![20190531214557](https://user-images.githubusercontent.com/31967654/58710112-2d7afa00-83ee-11e9-8e17-c02c29108d89.png)

不知道是不是主题没应用，背景还是白色的
![20190531214749](https://user-images.githubusercontent.com/31967654/58710157-484d6e80-83ee-11e9-88c4-31c13c61380a.png)
顺带提一个建议，关于OneDrive视频加载慢的确和地区网络有关系，但最重要的是Onedrive的单连接最快只有1.5Mbps，就是视频码率高于1500kbps都没法流畅播放。。。所以作为视频站来说限制还是挺高的，不过能白嫖一个5T储存池还带BGP中转的已经可以说非常好了。
所以这里可以试一试这个：
“让你在线看视频也能达到多线程下载的速度” https://github.com/cshuaimin/video-funnel
这个是针对Onedrive修改的，也是使用了python，就是通过多线程缓存来实现高速缓存。
https://github.com/vcheckzen/video-funnel
无知地问一下，这个功能有没有可能可以不通过本地的客户端实现？（估计不行，我看了这么多视频网站都是单线程缓存的，当然不排除是我真的见识短浅）

**Comment by mqdlzh** [comment]
![20190531223757](https://user-images.githubusercontent.com/31967654/58713351-f2c89000-83f4-11e9-896a-80bf9e6d5ae0.png)
![20190531223847](https://user-images.githubusercontent.com/31967654/58713360-f65c1700-83f4-11e9-9ecc-1ebf164220b6.png)
新的问题来了。。。3.0.4下绑定网盘会弹Bad Request。
现在的Cuteone的确还是有很多的问题，相对于Pyone或者简单一些的OneIndex在稳定性上还是有差距（安装过程可能也相对繁杂？不过对我来说还行，只要不是大问题基本还是可以靠度娘解决），但起码cuteone还在更新，其他目前都好几个月没动静了，issue也是堆了不少（像我这种小白闻风而来也是一大堆），最后打扰大佬了，感谢大佬抽出时间来看我这没用的issue。

**Comment by Hackxiaoya** [comment]
你不安装用户模块 或者在钩子位置 禁用用户模块 就不会出现用户登录。。搜索是你们要求的。不要就自己去模板改。

**Comment by Hackxiaoya** [comment]
你说的那个多线程的视频。是不可用的。因为他是先拉到他服务器。然后用他服务器做承载。这自然就不可取了。
