### ISSUE TITLE
error occurs when start to sync

### ISSUE THREAD

**Issue by hulb** [Hackxiaoya/CuteOne#56]
error log:

 Exception in thread Thread-351:
cuteone  | Traceback (most recent call last):
cuteone  |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
cuteone  |     self.run()
cuteone  |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
cuteone  |     self._target(*self._args, **self._kwargs)
cuteone  |   File "/www/wwwroot/CuteOne/app/task/syn/syn.py", line 120, in task_write
cuteone  |     "file": data["file"]["mimeType"],
cuteone  | KeyError: 'file'

**Comment by hulb** [comment]
and:

127.0.0.1 - - [18/Jul/2019 13:02:07] "POST /socket.io/?EIO=3&transport=polling&sid=47aa272c9b7d4396995abc88e70499af&t=1563454705428-4 HTTP/1.1" 500 -
cuteone  | Error on request:
cuteone  | Traceback (most recent call last):
cuteone  |   File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
cuteone  |     execute(self.server.app)
cuteone  |   File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
cuteone  |     application_iter = app(environ, start_response)
cuteone  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
cuteone  |     return self.wsgi_app(environ, start_response)
cuteone  |   File "/usr/local/lib/python3.7/site-packages/flask_socketio/__init__.py", line 44, in __call__
cuteone  |     start_response)
cuteone  |   File "/usr/local/lib/python3.7/site-packages/engineio/middleware.py", line 59, in __call__
cuteone  |     return self.engineio_app.handle_request(environ, start_response)
cuteone  |   File "/usr/local/lib/python3.7/site-packages/socketio/server.py", line 428, in handle_request
cuteone  |     return self.eio.handle_request(environ, start_response)
cuteone  |   File "/usr/local/lib/python3.7/site-packages/engineio/server.py", line 337, in handle_request
cuteone  |     socket = self._get_socket(sid)
cuteone  |   File "/usr/local/lib/python3.7/site-packages/engineio/server.py", line 521, in _get_socket
cuteone  |     raise KeyError('Session is disconnected')
cuteone  | KeyError: 'Session is disconnected'

**Comment by hulb** [comment]
sync continues

**Comment by Hackxiaoya** [comment]
这是你的一些py扩展没装

**Comment by Hackxiaoya** [comment]
这是你的一些py扩展没装

**Comment by hulb** [comment]
ok, thanks.
