### ISSUE TITLE
3.10版本，更换主题BUG

### ISSUE THREAD

**Issue by L245T** [Hackxiaoya/CuteOne#61]
通过网站后台更换主题后，自行上传的主题中public/layout.html文件不会生效，仅能够通过更改默认主题中的layout.html文件才可以生效

**Comment by Hackxiaoya** [comment]
后台压根没有主题可以更换。

**Comment by Hackxiaoya** [comment]
重启就会生效了吧。

**Comment by L245T** [comment]
> 重启就会生效了吧。

是这样的，我自己魔改了一下默认主题，然后将主题打包上传，在后台更换主题包后重启了程序，但是没有生效，然后我尝试了把默认主题的layout.html直接替换为我魔改的（默认主题中的其他文件均没有变更，后台仍然选择的是我上传的主题），然后重启程序，可以生效。

**Comment by Hackxiaoya** [comment]
嗯。
